### ISSUE TITLE
Filter function throwing error on token refresh

### ISSUE THREAD

**Issue by joshp23** [joshp23/ttrss-to-wallabag-v2#38]
it appears as if the error occurs only when the token gets refreshed. Here's how I got here:

1. Save an article to Wallabag using the button method. This will refresh the token if necessary.
2. Run a feed debug (fD) on a feed effected by a properly configured filter.
3. Check Wallabag, error logs, and debug.txt, all look good. 
4. Wait until the token expires, run fD on the effected feed again. Experience the following error:
```
 2020/03/08 15:03:13 [error] 1753#1753: *313266 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: There is already an active transaction in /var/www/ttrss/classes/pluginhost.php:335
Stack trace:
#0 /var/www/ttrss/classes/pluginhost.php(335): PDO->beginTransaction()
#1 /var/www/ttrss/classes/pluginhost.php(370): PluginHost->save_data('Wallabag_v2')
#2 /var/www/ttrss/plugins.local/wallabag_v2/init.php(255): PluginHost->set(Object(Wallabag_v2), 'wallabag_access...', 'REDACTED...')
#3 /var/www/ttrss/plugins.local/wallabag_v2/init.php(199): Wallabag_v2->_send('A thought i hav...', 'https://www.red...', 'filter')
#4 /var/www/ttrss/classes/rssutils.php(841): Wallabag_v2->hook_article_filter_action(Array, 'wallabag_v2_sen...')
#5 /var/www/ttrss/classes/feeds.php(846): RSSUtils::update_rss_feed(10, true)
#6 /var/www/ttrss/backend.php(123): Feeds->update_debugger()
#7 {main}
  thrown in /var/www/ttrss/classes/pluginhost.php on line 335" while reading upstream, client: MY_IP_ADDRESS, server: ttrss.example.com, request: "GET /backend.php?op=feeds&method=update_debugger&xdebug=1&csrf_token=REDACTED&action=do_update&feed_id=10&force_refetch=1&force_rehash=1 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "ttrss.example.com", referrer: "https://ttrss.example.com/backend.php?op=feeds&method=update_debugger&xdebug=1&csrf_token=REDACTED&action=do_update&feed_id=10&force_refetch=1&force_rehash=1"
```
Item 2 of the Stack trace indicates that the last line of code in the plugin that is called before the failure is line 255,   
https://github.com/joshp23/ttrss-to-wallabag-v2/blob/cbd634f866b3afa8a9e772f91dc76f38f3c47be2/wallabag_v2/init.php#L255  
which is attempting to save refresh token data. This error does not occure when saving and refreshing from the button. My guess here is that this is happening while TTRSS is saving articles to the database, throwing the error.

**Comment by joshp23** [comment]
fixed with https://github.com/joshp23/ttrss-to-wallabag-v2/commit/7b9e8f1ac942a0cd2664ee8a5524b8a10089df94
